### ISSUE TITLE
What could i do if i`d like to use local packages of TTS and SST?

### ISSUE THREAD

**Issue by ZJ-CAI** [tpulkit/txt2vid#8]
Could you pls tell me which python file should be modified. Thanks

**Comment by shubhamchandak94** [comment]
Hi, thanks for your interest in this!

For TTS, the main code is [inference_streaming_pipeline.py](https://github.com/tpulkit/txt2vid/blob/679b1672fb3221c6b5fe576a158974556047c201/Wav2Lip/inference_streaming_pipeline.py) where it sets the parameters and launches the threads for the Google or Resemble TTS. As you can see there the Resemble part requires multiple threads because it uses a callback mechanism to receive the audio. So in your case the google TTS path might be more straightforward to emulate. The actual thread handler functions which do the TTS calls are in [thread_handlers.py](https://github.com/tpulkit/txt2vid/blob/679b1672fb3221c6b5fe576a158974556047c201/Wav2Lip/inference_streaming_pipeline.py). The function names are self-explanatory, you can focus on `text_input_google_thread_handler`.

STT is run on the sender end, so it's in a different part of the codebase. The file is [input_stream_socket.py](https://github.com/tpulkit/txt2vid/blob/679b1672fb3221c6b5fe576a158974556047c201/input_stream_socket.py) and you will want to focus on the code that runs when `text_input_from == 'Google'`.

Let us know if you have further questions, we'll be happy to help.

Shubham

**Comment by ZJ-CAI** [comment]
Thank you for your detailed explanation. It really helps a lot, thank you once more!
